Add the ability to specific the device name
mvdan/libaccesspoint pull request #12
Opened 2016-12-29 07:56 UTC by peteroid

As S7 can have AP and Wifi open at the same time, there is a device called `swlan0` for AP. Therefore, the fallback device name, `wlan0` is not working on S7.

connect #11

2016-12-29 12:13 UTC, mvdan commented
> connect #11 

Surely you mean "Fixes #11"?

2016-12-29 12:15 UTC, mvdan commented
In a way, I would like this to work without hacks on the user side like this. From the application code, how do you know whether to use the default or specify `swlan0`? If you have to implement logic to detect the device or use a second fallback device name, this logic should go in the library.

Have you tried either of those?

2016-12-29 12:22 UTC, peteroid commented
Hi,

I didn't try neither. I just tried this on my S7 and it works. So I wanna
see what I can help with this issue.

On Dec 29, 2016 8:15 PM, "Daniel Martí" <notifications@github.com> wrote:

> In a way, I would like this to work without hacks on the user side like
> this. From the application code, how do you know whether to use the default
> or specify swlan0? If you have to implement logic to detect the device or
> use a second fallback device name, this logic should go in the library.
>
> Have you tried either of those?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mvdan/accesspoint/pull/12#issuecomment-269622155>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AMGfJNNXSRzTeOl7NG3TEnlMA8XVbILKks5rM6RFgaJpZM4LXacD>
> .
>

2016-12-29 15:31 UTC, mvdan commented
Sure - the current way is definitely far from ideal. My point is that this solution doesn't really fix it for apps that want to work on all devices. Each app would have to reimplement this logic.

I think those two options I mentioned there could work. I don't have any devices that have a device name other than `wlan0`, so all I can do is review code.

2017-02-06 12:39 UTC, mvdan requested changes
As said above, I'd rather not leave this up to the app to figure out. This is the access point library, so the logic to decide what device name to use should be here.

If we can't figure it out automatically, how would an app?

Unless what you mean is give up and ask the user manually. That's worse, in my opinion.

2017-02-11 06:18 UTC, peteroid commented
You are right. Then, I should figure out a way for getting the `arp` information on such special devices like Samsung S7.

2017-02-11 17:59 UTC, mvdan commented
@peteroid yep. Note that the library already has a mechanism for this, but it uses the MAC address of the device (of its wifi devices) and unfortunately that is hidden in newer Android versions.

I haven't figured a way to do it on newer Android versions yet. That would effectively solve this issue.

2017-02-11 18:01 UTC, mvdan commented
Another note - if it really isn't possible to do this automagically (haven't looked hard enough to know), we could also ship a table of Android devices that we know have device names other than `wlan0`. Assuming that the only factor is the device. Perhaps the Android version also affects the value?

Alternatively, a number of names could be tried if that would work - `wlan0`, `swlan0`, `wlp3s0`...

2017-03-17 12:48 UTC, mvdan commented
Since this PR is inactive, let's move the discussion to #11.

2017-03-17 12:48 UTC, closed without merging