Possibility of enable 5Ghz through java reflection
mvdan/libaccesspoint pull request #14
Opened 2017-04-17 15:37 UTC by forlayo

Added the possibility of enable 5Ghz through java reflection ( Maybe it will only works on Android 6 only ).

2017-04-17 15:38 UTC, mvdan commented
Did you try this? Does it work? (can't try it myself because this lib is currently broken on 7.1, which is what I run)

2017-04-17 15:39 UTC, mvdan commented
Also, add "Fixes #13" in the body of the commit message so that the issue will be closed when this is merged.

2017-04-17 15:43 UTC, forlayo commented
Yep, it works; I've been sucessfully used it on my Nexus 6p and Nexus 5x devices. Can I modify the commit here? I'm leaving the office right now and I haven't access to the git console right now :(

2017-04-17 17:04 UTC, mvdan commented
I don't think the web UI lets you modify commits - but that's okay, I'm not in a rush to merge this. I'll review the code now.

2017-04-17 17:11 UTC, mvdan reviewed
I would change the API to not be centralized on 5GHz. Done like this, once you switch to 5GHz there is no way to go back to 2.4GHz.

Perhaps do something like:

```
public enum Band {
    2GHz, 5GHz
}

public static boolean setBand(Band band) { ...
```

2017-04-17 17:11 UTC, mvdan commented on library/src/main/java/cc/mvdan/accesspoint/WifiApControl.java
> +	}
This should only check if the field exists, not change it.

2017-04-17 17:11 UTC, mvdan commented on library/src/main/java/cc/mvdan/accesspoint/WifiApControl.java
> +	public static boolean setField(Object targetObject, String fieldName, Object fieldValue) {
private

2017-04-17 17:11 UTC, mvdan commented on library/src/main/java/cc/mvdan/accesspoint/WifiApControl.java
> +	 */
Use shorter method docs, like in the rest of the code:

```
// Checks if 5Ghz band is available to create an accesspoint.
```

Same for the rest of the code you added.

2017-04-17 17:11 UTC, mvdan commented on library/src/main/java/cc/mvdan/accesspoint/WifiApControl.java
> +	}
What about switching to 2GHz?

2017-04-17 17:11 UTC, mvdan commented on library/src/main/java/cc/mvdan/accesspoint/WifiApControl.java
> +		}
Why is this `while` needed? (just curious)

2017-04-17 17:12 UTC, mvdan commented
And thanks for contributing! :)

2017-04-19 12:06 UTC, mvdan requested changes
I also just realised that there is no way to get the current band. As it is now, this change has limited use and it exposes too much.

2017-04-28 09:25 UTC, mvdan commented
Bump @forlayo

2017-05-31 09:52 UTC, mvdan commented
Ping @forlayo - happy to get the feature merged, but not in the current state. Do you have time to fix the pull request?

2017-10-30 14:40 UTC, mvdan commented
Still no answer - closing.

2017-10-30 14:40 UTC, closed without merging